//! E32B-015: lockfile v2 SHA-256 integrity and frozen installs.

#![cfg(unix)]

mod common;

use common::{taida_bin, unique_temp_dir, write_file};
use std::fs;
use std::os::unix::fs::symlink;
use std::path::{Path, PathBuf};
use std::process::Command;

fn setup_path_dep_project(label: &str) -> (PathBuf, PathBuf) {
    let project = unique_temp_dir(label);
    let dep = project.join("dep");
    fs::create_dir_all(&dep).expect("create dep");
    write_file(
        &project.join("packages.tdm"),
        r#"
name <= "e32b015-consumer"
version <= "e.1"
deps <= @(
  demo <= @(path <= "./dep")
)
"#,
    );
    write_file(&project.join("main.td"), "stdout(\"consumer\")\n");
    write_file(
        &dep.join("packages.tdm"),
        "name <= \"demo\"\nversion <= \"e.1\"\n",
    );
    write_file(
        &dep.join("main.td"),
        r#"Value <= "lock-ok"
<<< @(Value)
"#,
    );
    (project, dep)
}

fn run(project: &Path, args: &[&str]) -> std::process::Output {
    Command::new(taida_bin())
        .args(args)
        .current_dir(project)
        .output()
        .unwrap_or_else(|_| panic!("run taida {}", args.join(" ")))
}

fn assert_stderr_contains(output: &std::process::Output, needle: &str, label: &str) {
    assert!(!output.status.success(), "{label} should fail");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(needle),
        "{label} should contain {needle}, got: {stderr}"
    );
}

#[test]
fn e32b_015_install_writes_v2_sha256_and_frozen_detects_drift() {
    let (project, dep) = setup_path_dep_project("e32b_015_frozen");
    let first = run(&project, &["ingot", "install"]);
    assert!(
        first.status.success(),
        "first install should succeed: {}",
        String::from_utf8_lossy(&first.stderr)
    );

    let lock_path = project.join(".taida/taida.lock");
    let lock = fs::read_to_string(&lock_path).expect("read lock");
    assert!(lock.contains("# lockfile-version: 2"), "{lock}");
    assert!(lock.contains("integrity = \"sha256:"), "{lock}");
    assert!(!lock.contains("fnv1a:"), "{lock}");

    write_file(
        &dep.join("main.td"),
        r#"Value <= "changed"
<<< @(Value)
"#,
    );
    let frozen = run(&project, &["ingot", "install", "--frozen"]);
    assert_stderr_contains(
        &frozen,
        "[E32K2_LOCKFILE_INTEGRITY_MISMATCH]",
        "frozen drift",
    );

    let _ = fs::remove_dir_all(&project);
}

#[test]
fn e32b_015_legacy_v1_fnv1a_lockfile_rejected() {
    let (project, _dep) = setup_path_dep_project("e32b_015_v1_reject");
    fs::create_dir_all(project.join(".taida")).expect("create .taida");
    write_file(
        &project.join(".taida/taida.lock"),
        r#"# taida.lock -- auto-generated by taida ingot install
# lockfile-version: 1

[[package]]
name = "demo"
version = "0.0.0-local"
source = "path:./dep"
integrity = "fnv1a:0000000000000001"
"#,
    );

    let output = run(&project, &["ingot", "install"]);
    assert_stderr_contains(&output, "[E32K2_LOCKFILE_V1_REJECTED]", "legacy lockfile");

    let _ = fs::remove_dir_all(&project);
}

#[test]
fn e32b_015_migrate_lockfile_rewrites_installed_tree_to_sha256() {
    let (project, dep) = setup_path_dep_project("e32b_015_migrate");
    let deps_dir = project.join(".taida/deps");
    fs::create_dir_all(&deps_dir).expect("create deps");
    symlink(&dep, deps_dir.join("demo")).expect("symlink installed dep");
    write_file(
        &project.join(".taida/taida.lock"),
        r#"# taida.lock -- auto-generated by taida ingot install
# lockfile-version: 1

[[package]]
name = "demo"
version = "0.0.0-local"
source = "path:./dep"
integrity = "fnv1a:0000000000000001"
"#,
    );

    let migrate = run(&project, &["ingot", "migrate-lockfile"]);
    assert!(
        migrate.status.success(),
        "migration should succeed: {}",
        String::from_utf8_lossy(&migrate.stderr)
    );
    let lock = fs::read_to_string(project.join(".taida/taida.lock")).expect("read migrated lock");
    assert!(lock.contains("# lockfile-version: 2"), "{lock}");
    assert!(lock.contains("integrity = \"sha256:"), "{lock}");
    assert!(!lock.contains("fnv1a:"), "{lock}");

    let frozen = run(&project, &["ingot", "install", "--frozen"]);
    assert!(
        frozen.status.success(),
        "migrated lockfile should satisfy frozen install: {}",
        String::from_utf8_lossy(&frozen.stderr)
    );

    let _ = fs::remove_dir_all(&project);
}

/// E32B-083: non-frozen `taida ingot install` must accept legitimate drift
/// (path dep contents changed -> integrity differs) and rewrite the lockfile,
/// instead of failing with `[E32K2_LOCKFILE_INTEGRITY_MISMATCH]` from
/// `validate_resolved_bindings`. Triple equality is reserved for `--frozen`.
#[test]
fn e32b_083_non_frozen_install_accepts_drift_and_rewrites_lockfile() {
    let (project, dep) = setup_path_dep_project("e32b_083_drift_rewrite");
    let first = run(&project, &["ingot", "install"]);
    assert!(
        first.status.success(),
        "first install should succeed: {}",
        String::from_utf8_lossy(&first.stderr)
    );

    let lock_path = project.join(".taida/taida.lock");
    let lock_before = fs::read_to_string(&lock_path).expect("read lock before drift");
    let integrity_before = lock_before
        .lines()
        .find(|line| line.trim_start().starts_with("integrity = \"sha256:"))
        .expect("first install must write sha256 integrity")
        .to_string();

    write_file(
        &dep.join("main.td"),
        r#"Value <= "drift-after"
<<< @(Value)
"#,
    );

    let second = run(&project, &["ingot", "install"]);
    assert!(
        second.status.success(),
        "non-frozen install must succeed under drift, got stderr: {}",
        String::from_utf8_lossy(&second.stderr)
    );
    let stderr = String::from_utf8_lossy(&second.stderr);
    assert!(
        !stderr.contains("[E32K2_LOCKFILE_INTEGRITY_MISMATCH]"),
        "non-frozen install must not reject legitimate drift, stderr={stderr}"
    );

    let lock_after = fs::read_to_string(&lock_path).expect("read lock after drift");
    let integrity_after = lock_after
        .lines()
        .find(|line| line.trim_start().starts_with("integrity = \"sha256:"))
        .expect("rewrite must keep sha256 integrity")
        .to_string();
    assert_ne!(
        integrity_before, integrity_after,
        "non-frozen install must rewrite drifted integrity; before={integrity_before} after={integrity_after}"
    );

    let _ = fs::remove_dir_all(&project);
}

/// A lockfile whose integrity claims `sha256:` but is not a canonical
/// 64-lowercase-hex payload must be rejected by `Lockfile::read`, not
/// silently invalidated by `is_up_to_date` and rewritten by the resolver.
/// Migration must go through `taida ingot migrate-lockfile`.
#[test]
fn e32b_044_malformed_sha256_lockfile_rejected_before_resolve() {
    let (project, _dep) = setup_path_dep_project("e32b_044_malformed_sha256");
    fs::create_dir_all(project.join(".taida")).expect("create .taida");
    write_file(
        &project.join(".taida/taida.lock"),
        r#"# taida.lock -- auto-generated by taida ingot install
# lockfile-version: 2

[[package]]
name = "demo"
version = "0.0.0-local"
source = "path:./dep"
integrity = "sha256:0"
"#,
    );

    let output = run(&project, &["ingot", "install"]);
    assert_stderr_contains(
        &output,
        "[E32K2_LOCKFILE_INTEGRITY_MISMATCH]",
        "malformed sha256 lockfile",
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("malformed integrity"),
        "expected `malformed integrity` hint in stderr, got: {stderr}"
    );

    let _ = fs::remove_dir_all(&project);
}

/// A malformed sha256 lockfile must not be silently rewritten by a
/// successful `taida ingot install`. The original tampered file must remain
/// on disk untouched until `taida ingot migrate-lockfile` is invoked.
#[test]
fn e32b_063_malformed_sha256_lockfile_not_silently_overwritten() {
    let (project, _dep) = setup_path_dep_project("e32b_063_no_silent_migrate");
    fs::create_dir_all(project.join(".taida")).expect("create .taida");
    let original = r#"# taida.lock -- auto-generated by taida ingot install
# lockfile-version: 2

[[package]]
name = "demo"
version = "0.0.0-local"
source = "path:./dep"
integrity = "sha256:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
"#;
    write_file(&project.join(".taida/taida.lock"), original);

    let output = run(&project, &["ingot", "install"]);
    assert!(
        !output.status.success(),
        "install must fail rather than silently rewriting a malformed lockfile"
    );

    let still_on_disk = fs::read_to_string(project.join(".taida/taida.lock"))
        .expect("read lockfile after rejected install");
    assert_eq!(
        still_on_disk, original,
        "tampered lockfile must remain on disk; resolver must not auto-migrate"
    );

    let _ = fs::remove_dir_all(&project);
}

#[test]
fn e32b_015_path_dependency_binding_builds_on_all_compile_backends() {
    let (project, _dep) = setup_path_dep_project("e32b_015_binding");
    let install = run(&project, &["ingot", "install"]);
    assert!(
        install.status.success(),
        "install should succeed: {}",
        String::from_utf8_lossy(&install.stderr)
    );
    write_file(
        &project.join("main.td"),
        r#">>> demo => @(Value)
stdout(Value)
"#,
    );

    let interp = run(&project, &["main.td"]);
    assert!(
        interp.status.success() && String::from_utf8_lossy(&interp.stdout).contains("lock-ok"),
        "interpreter import should see installed binding: stdout={} stderr={}",
        String::from_utf8_lossy(&interp.stdout),
        String::from_utf8_lossy(&interp.stderr)
    );

    for (target, out) in [
        ("js", "out.mjs"),
        ("native", "out-native"),
        ("wasm-min", "out.wasm"),
    ] {
        let output = Command::new(taida_bin())
            .args(["build", target, "main.td", "-o", out])
            .current_dir(&project)
            .output()
            .unwrap_or_else(|_| panic!("run taida build {target}"));
        assert!(
            output.status.success(),
            "{target} build should resolve installed binding: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let _ = fs::remove_dir_all(&project);
}
