//! `native/addon.lock.toml` read/write for RC2.6 addon publish flow.
//!
//! `.dev/RC2_6_DESIGN.md` v2 introduces a **new file** alongside the
//! frozen `native/addon.toml`: the addon lockfile. The frozen ABI v1
//! manifest (`[library.prebuild]`) is never mutated by `taida publish`;
//! instead, the per-host `sha256:<hex>` rows live in this lockfile and
//! are uploaded as a GitHub Release asset so `taida install` can fetch
//! them for any tagged version without checking out the source tree.
//!
//! This solves the tag/commit ordering problem spelled out in RC2.6B-005:
//! since `taida install` downloads the **tarball at the exact tag**, any
//! host-specific SHA-256 committed after the tag would be invisible to
//! the installer. By splitting the data into a release asset, we
//! preserve the "tarball is immutable" invariant while still letting
//! multiple hosts contribute their digests over time.
//!
//! # Schema (v1)
//!
//! ```toml
//! # native/addon.lock.toml
//! # Generated by `taida publish --target rust-addon`.
//! # Do NOT edit manually.
//!
//! [targets]
//! "x86_64-unknown-linux-gnu" = "sha256:abc..."
//! "aarch64-apple-darwin"     = "sha256:def..."
//! ```
//!
//! * The presence of the file is the **publish marker**. No other
//!   top-level keys are accepted in v1.
//! * `[targets]` keys are host triples, values are the exact
//!   `"sha256:<64 lowercase hex>"` strings produced by CI during the
//!   release workflow (C14 tag-only publish delegates SHA computation
//!   to the addon `release.yml`; the CLI never hashes local cdylibs).
//! * Future fields (signatures, timestamps, version-pin) are reserved
//!   for v2 and SHOULD be added as new sections rather than by bending
//!   the `[targets]` schema.
//!
//! # Parser contract
//!
//! Like `src/addon/manifest.rs`, this module is a **hand-written TOML
//! subset parser** (RC2.6 Should Fix S1: "no new TOML crate
//! dependency"). It accepts:
//!
//! * Blank lines and `#` line comments.
//! * `[targets]` section header (exactly once; duplicates are rejected).
//! * `"<key>" = "<value>"` pairs inside `[targets]`. Keys MUST be
//!   double-quoted (host triples contain `-` but the quoting removes
//!   any ambiguity with other TOML subsets we may add later).
//! * Values MUST be double-quoted strings with the `"sha256:"` prefix
//!   followed by 64 lowercase hex characters.
//!
//! Anything else is an error — silent acceptance is forbidden so that
//! a malformed lockfile cannot downgrade integrity checks.
//!
//! # Merge semantics (`write_lockfile`)
//!
//! `write_lockfile` is **append-only** at the per-host level:
//!
//! * Existing entries for OTHER host triples are preserved verbatim.
//! * The caller-supplied host row is inserted (or overwrites any row
//!   with the same triple key).
//!
//! This matches the CI matrix model where each host runner contributes
//! its own digest independently. Wiping entries for other hosts would
//! race against concurrent runners; that is why the old-style "write
//! once from one machine" model is rejected.

use std::collections::BTreeMap;
use std::fmt;
use std::path::{Path, PathBuf};

/// Parsed contents of `native/addon.lock.toml`.
///
/// Uses `BTreeMap` so that serialised output has a stable, lexicographic
/// ordering of host triples. This is required for determinism:
/// `cargo test` runs in parallel and two hosts writing to the same
/// lockfile must produce identical byte output regardless of OS
/// hash-map randomisation.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AddonLockfile {
    /// Host triple -> `"sha256:<64 hex>"`.
    pub targets: BTreeMap<String, String>,
}

impl AddonLockfile {
    /// Construct an empty lockfile.
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert or overwrite a per-host SHA-256 entry.
    ///
    /// The triple is stored verbatim; validation should happen at the
    /// call site (the parser validates on read; CI is responsible for
    /// producing the canonical `"sha256:<hex>"` format on write).
    pub fn set_target(&mut self, host_triple: impl Into<String>, sha: impl Into<String>) {
        self.targets.insert(host_triple.into(), sha.into());
    }

    /// Look up a per-host SHA-256 entry.
    pub fn get_target(&self, host_triple: &str) -> Option<&str> {
        self.targets.get(host_triple).map(|s| s.as_str())
    }

    /// Returns true when no per-host entries exist.
    pub fn is_empty(&self) -> bool {
        self.targets.is_empty()
    }
}

/// Errors raised by [`read_lockfile`] / [`write_lockfile`].
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum LockfileError {
    /// `std::fs::read_to_string` / `std::fs::write` failed.
    Io { path: PathBuf, message: String },
    /// Parse-time syntax error with one-indexed line number.
    Syntax {
        path: PathBuf,
        line: usize,
        message: String,
    },
    /// `[targets]` section header was declared more than once.
    DuplicateTargetsSection { path: PathBuf, line: usize },
    /// Two rows collided on the same host-triple key within a single
    /// `[targets]` section.
    DuplicateTargetKey {
        path: PathBuf,
        line: usize,
        host_triple: String,
    },
    /// An unknown `[section]` header appeared.
    UnknownSection {
        path: PathBuf,
        line: usize,
        name: String,
    },
    /// Value is not of the shape `"sha256:<64 lowercase hex>"`.
    InvalidSha256Format {
        path: PathBuf,
        line: usize,
        host_triple: String,
        value: String,
    },
    /// A top-level key appeared outside of any `[section]`.
    UnexpectedTopLevelKey {
        path: PathBuf,
        line: usize,
        key: String,
    },
}

impl fmt::Display for LockfileError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, message } => write!(
                f,
                "addon lockfile error: I/O failure on '{}': {}",
                path.display(),
                message
            ),
            Self::Syntax {
                path,
                line,
                message,
            } => write!(
                f,
                "addon lockfile error: syntax error in '{}' at line {}: {}",
                path.display(),
                line,
                message
            ),
            Self::DuplicateTargetsSection { path, line } => write!(
                f,
                "addon lockfile error: '[targets]' declared more than once in '{}' (second occurrence at line {})",
                path.display(),
                line
            ),
            Self::DuplicateTargetKey {
                path,
                line,
                host_triple,
            } => write!(
                f,
                "addon lockfile error: duplicate target '{}' in '{}' at line {}",
                host_triple,
                path.display(),
                line
            ),
            Self::UnknownSection { path, line, name } => write!(
                f,
                "addon lockfile error: unknown section '[{}]' in '{}' at line {} (only '[targets]' is allowed in v1)",
                name,
                path.display(),
                line
            ),
            Self::InvalidSha256Format {
                path,
                line,
                host_triple,
                value,
            } => write!(
                f,
                "addon lockfile error: target '{}' in '{}' at line {} has value '{}' which is not 'sha256:' + 64 lowercase hex characters",
                host_triple,
                path.display(),
                line,
                value
            ),
            Self::UnexpectedTopLevelKey { path, line, key } => write!(
                f,
                "addon lockfile error: top-level key '{}' in '{}' at line {} is not allowed outside of '[targets]'",
                key,
                path.display(),
                line
            ),
        }
    }
}

impl std::error::Error for LockfileError {}

/// Validates that a string is exactly `"sha256:" + 64 lowercase hex
/// characters` and nothing else. Used by both the parser (read side)
/// and [`write_lockfile`] (write side, defensive).
fn is_valid_sha256_tag(value: &str) -> bool {
    let Some(hex) = value.strip_prefix("sha256:") else {
        return false;
    };
    if hex.len() != 64 {
        return false;
    }
    hex.chars()
        .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c))
}

/// Read `native/addon.lock.toml` at `path`. A missing file is treated
/// as an **empty** lockfile (equivalent to `AddonLockfile::new()`), so
/// the caller can always use the merge pattern
/// `let mut lock = read_lockfile(path)?; lock.set_target(...); write_lockfile(path, &lock)?;`.
pub fn read_lockfile(path: &Path) -> Result<AddonLockfile, LockfileError> {
    if !path.exists() {
        return Ok(AddonLockfile::new());
    }
    let source = std::fs::read_to_string(path).map_err(|e| LockfileError::Io {
        path: path.to_path_buf(),
        message: e.to_string(),
    })?;
    parse_lockfile_str(path, &source)
}

/// Parse a lockfile source string. Exposed for unit tests that want
/// to exercise the parser without touching the filesystem.
pub fn parse_lockfile_str(path: &Path, source: &str) -> Result<AddonLockfile, LockfileError> {
    let mut lock = AddonLockfile::new();

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum Section {
        None,
        Targets,
    }

    let mut section = Section::None;
    let mut saw_targets_header = false;

    for (idx, raw_line) in source.lines().enumerate() {
        let line_no = idx + 1;
        let line = raw_line.trim();

        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Section header.
        if let Some(rest) = line.strip_prefix('[') {
            let name = rest
                .strip_suffix(']')
                .ok_or_else(|| LockfileError::Syntax {
                    path: path.to_path_buf(),
                    line: line_no,
                    message: "section header missing ']'".to_string(),
                })?;
            let name = name.trim();
            match name {
                "targets" => {
                    if saw_targets_header {
                        return Err(LockfileError::DuplicateTargetsSection {
                            path: path.to_path_buf(),
                            line: line_no,
                        });
                    }
                    saw_targets_header = true;
                    section = Section::Targets;
                }
                other => {
                    return Err(LockfileError::UnknownSection {
                        path: path.to_path_buf(),
                        line: line_no,
                        name: other.to_string(),
                    });
                }
            }
            continue;
        }

        // Key = value pair.
        let (key_raw, value_raw) = line.split_once('=').ok_or_else(|| LockfileError::Syntax {
            path: path.to_path_buf(),
            line: line_no,
            message: "expected 'key = value' or '[section]'".to_string(),
        })?;
        let key_raw = key_raw.trim();
        let value_raw = strip_inline_comment(value_raw).trim();

        // Key must be double-quoted.
        let key = key_raw
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
            .ok_or_else(|| LockfileError::Syntax {
                path: path.to_path_buf(),
                line: line_no,
                message: format!("key '{}' must be a double-quoted string", key_raw),
            })?;
        if key.is_empty() {
            return Err(LockfileError::Syntax {
                path: path.to_path_buf(),
                line: line_no,
                message: "key must not be empty".to_string(),
            });
        }
        if key.contains('"') {
            return Err(LockfileError::Syntax {
                path: path.to_path_buf(),
                line: line_no,
                message: format!("key '{}' must not contain embedded quotes", key),
            });
        }

        // Value must be double-quoted.
        let value = value_raw
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
            .ok_or_else(|| LockfileError::Syntax {
                path: path.to_path_buf(),
                line: line_no,
                message: format!("value for '{}' must be a double-quoted string", key),
            })?;
        if value.contains('"') {
            return Err(LockfileError::Syntax {
                path: path.to_path_buf(),
                line: line_no,
                message: format!("value for '{}' must not contain embedded quotes", key),
            });
        }

        match section {
            Section::None => {
                return Err(LockfileError::UnexpectedTopLevelKey {
                    path: path.to_path_buf(),
                    line: line_no,
                    key: key.to_string(),
                });
            }
            Section::Targets => {
                if !is_valid_sha256_tag(value) {
                    return Err(LockfileError::InvalidSha256Format {
                        path: path.to_path_buf(),
                        line: line_no,
                        host_triple: key.to_string(),
                        value: value.to_string(),
                    });
                }
                if lock.targets.contains_key(key) {
                    return Err(LockfileError::DuplicateTargetKey {
                        path: path.to_path_buf(),
                        line: line_no,
                        host_triple: key.to_string(),
                    });
                }
                lock.targets.insert(key.to_string(), value.to_string());
            }
        }
    }

    Ok(lock)
}

fn strip_inline_comment(value: &str) -> &str {
    // Strip `# comment` tails when the `#` is NOT inside a "...".
    // We tolerate the simple case only: count quotes before the `#`
    // and, if even, truncate. This mirrors src/addon/manifest.rs.
    if let Some(idx) = value.find('#') {
        let before = &value[..idx];
        if before.matches('"').count().is_multiple_of(2) {
            return before;
        }
    }
    value
}

/// Serialise an `AddonLockfile` into the canonical on-disk form.
/// Used by [`write_lockfile`] and exposed as `pub(crate)` so unit
/// tests can check round-trip behaviour without touching the
/// filesystem.
pub(crate) fn render_lockfile(lock: &AddonLockfile) -> String {
    let mut out = String::new();
    out.push_str(
        "# native/addon.lock.toml\n\
         # Generated by `taida publish --target rust-addon`.\n\
         # Do NOT edit manually. Committed for reproducibility; also uploaded\n\
         # as a GitHub Release asset so `taida install` can fetch it for any\n\
         # tagged version without checking out the repository.\n\
         \n\
         [targets]\n",
    );
    // BTreeMap guarantees lexicographic ordering.
    for (host, sha) in &lock.targets {
        out.push('"');
        out.push_str(host);
        out.push_str("\" = \"");
        out.push_str(sha);
        out.push_str("\"\n");
    }
    out
}

/// Write (or append-merge) an addon lockfile at `path`.
///
/// **Merge semantics**: the existing file at `path` (if any) is read
/// first; its entries are preserved for any host triple **not** already
/// present in `lock`. Entries in `lock` then overwrite the corresponding
/// rows (by host triple). The final merged state is written back.
///
/// This guarantees that a single-host local `taida publish` never wipes
/// out the per-host digests already contributed by the CI matrix, and
/// that two CI runners updating the lockfile concurrently produce a
/// deterministic outcome (both entries end up in the file after the
/// eventual-consistent merge).
///
/// On I/O failure, returns a structured error **without partial
/// writes** beyond what the underlying filesystem implementation may
/// buffer.
pub fn write_lockfile(path: &Path, lock: &AddonLockfile) -> Result<(), LockfileError> {
    // Validate values defensively so a malformed in-memory struct
    // can never leak a corrupt lockfile to disk.
    for (host, sha) in &lock.targets {
        if !is_valid_sha256_tag(sha) {
            return Err(LockfileError::InvalidSha256Format {
                path: path.to_path_buf(),
                line: 0,
                host_triple: host.clone(),
                value: sha.clone(),
            });
        }
    }

    let existing = read_lockfile(path)?;
    let mut merged = existing;
    for (host, sha) in &lock.targets {
        merged.targets.insert(host.clone(), sha.clone());
    }

    if let Some(parent) = path.parent()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent).map_err(|e| LockfileError::Io {
            path: parent.to_path_buf(),
            message: e.to_string(),
        })?;
    }

    let rendered = render_lockfile(&merged);
    std::fs::write(path, rendered).map_err(|e| LockfileError::Io {
        path: path.to_path_buf(),
        message: e.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn tmp(label: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "taida_lockfile_{}_{}_{}",
            label,
            std::process::id(),
            nanos
        ))
    }

    #[test]
    fn is_valid_sha256_tag_accepts_canonical() {
        let hex = "0".repeat(64);
        assert!(is_valid_sha256_tag(&format!("sha256:{hex}")));
    }

    #[test]
    fn is_valid_sha256_tag_rejects_wrong_length() {
        assert!(!is_valid_sha256_tag("sha256:abc"));
        assert!(!is_valid_sha256_tag(&format!("sha256:{}", "a".repeat(63))));
        assert!(!is_valid_sha256_tag(&format!("sha256:{}", "a".repeat(65))));
    }

    #[test]
    fn is_valid_sha256_tag_rejects_uppercase() {
        assert!(!is_valid_sha256_tag(&format!("sha256:{}", "A".repeat(64))));
    }

    #[test]
    fn is_valid_sha256_tag_rejects_missing_prefix() {
        assert!(!is_valid_sha256_tag(&"a".repeat(64)));
    }

    #[test]
    fn read_lockfile_missing_file_returns_empty() {
        let p = tmp("missing").join("addon.lock.toml");
        let lock = read_lockfile(&p).expect("missing file should yield empty lockfile");
        assert!(lock.is_empty());
    }

    #[test]
    fn parse_lockfile_str_round_trip_single_host() {
        let src = "[targets]\n\"x86_64-unknown-linux-gnu\" = \"sha256:".to_string()
            + &"b".repeat(64)
            + "\"\n";
        let lock = parse_lockfile_str(Path::new("mem"), &src).expect("parse");
        assert_eq!(lock.targets.len(), 1);
        assert_eq!(
            lock.get_target("x86_64-unknown-linux-gnu"),
            Some(&*format!("sha256:{}", "b".repeat(64)))
        );
    }

    #[test]
    fn parse_lockfile_str_preserves_multi_host() {
        let src = format!(
            "# header comment\n\
             [targets]\n\
             \"aarch64-apple-darwin\" = \"sha256:{}\"\n\
             \"x86_64-unknown-linux-gnu\" = \"sha256:{}\"\n",
            "a".repeat(64),
            "c".repeat(64)
        );
        let lock = parse_lockfile_str(Path::new("mem"), &src).expect("parse");
        assert_eq!(lock.targets.len(), 2);
        assert!(lock.get_target("aarch64-apple-darwin").is_some());
        assert!(lock.get_target("x86_64-unknown-linux-gnu").is_some());
    }

    #[test]
    fn parse_lockfile_str_rejects_unquoted_key() {
        let src = format!(
            "[targets]\nx86_64-unknown-linux-gnu = \"sha256:{}\"\n",
            "a".repeat(64)
        );
        let err = parse_lockfile_str(Path::new("mem"), &src).unwrap_err();
        match err {
            LockfileError::Syntax { message, .. } => {
                assert!(message.contains("double-quoted"), "got: {message}");
            }
            other => panic!("expected Syntax, got {other:?}"),
        }
    }

    #[test]
    fn parse_lockfile_str_rejects_unknown_section() {
        let src = "[signatures]\n\"x86_64-unknown-linux-gnu\" = \"gpg:foo\"\n";
        let err = parse_lockfile_str(Path::new("mem"), src).unwrap_err();
        match err {
            LockfileError::UnknownSection { name, .. } => {
                assert_eq!(name, "signatures");
            }
            other => panic!("expected UnknownSection, got {other:?}"),
        }
    }

    #[test]
    fn parse_lockfile_str_rejects_invalid_sha256() {
        let src = "[targets]\n\"x86_64-unknown-linux-gnu\" = \"md5:deadbeef\"\n";
        let err = parse_lockfile_str(Path::new("mem"), src).unwrap_err();
        match err {
            LockfileError::InvalidSha256Format { value, .. } => {
                assert_eq!(value, "md5:deadbeef");
            }
            other => panic!("expected InvalidSha256Format, got {other:?}"),
        }
    }

    #[test]
    fn parse_lockfile_str_rejects_duplicate_targets_section() {
        let src = format!(
            "[targets]\n\
             \"x86_64-unknown-linux-gnu\" = \"sha256:{}\"\n\
             [targets]\n\
             \"aarch64-apple-darwin\" = \"sha256:{}\"\n",
            "a".repeat(64),
            "b".repeat(64)
        );
        let err = parse_lockfile_str(Path::new("mem"), &src).unwrap_err();
        matches!(err, LockfileError::DuplicateTargetsSection { .. });
    }

    #[test]
    fn parse_lockfile_str_rejects_duplicate_target_key_in_one_section() {
        let src = format!(
            "[targets]\n\
             \"x86_64-unknown-linux-gnu\" = \"sha256:{}\"\n\
             \"x86_64-unknown-linux-gnu\" = \"sha256:{}\"\n",
            "a".repeat(64),
            "b".repeat(64)
        );
        let err = parse_lockfile_str(Path::new("mem"), &src).unwrap_err();
        match err {
            LockfileError::DuplicateTargetKey { host_triple, .. } => {
                assert_eq!(host_triple, "x86_64-unknown-linux-gnu");
            }
            other => panic!("expected DuplicateTargetKey, got {other:?}"),
        }
    }

    #[test]
    fn parse_lockfile_str_rejects_top_level_key() {
        let src = format!("\"stray\" = \"sha256:{}\"\n", "a".repeat(64));
        let err = parse_lockfile_str(Path::new("mem"), &src).unwrap_err();
        matches!(err, LockfileError::UnexpectedTopLevelKey { .. });
    }

    #[test]
    fn parse_lockfile_str_accepts_inline_comments() {
        let src = format!(
            "[targets] # host digests\n\
             \"x86_64-unknown-linux-gnu\" = \"sha256:{}\"  # from local publish\n",
            "d".repeat(64)
        );
        // Inline comment handling: trailing `[targets] # host digests`
        // does not strip because section header only allows pure
        // `[name]`. Adjust the test to not rely on inline comments
        // inside section headers — the documented grammar is strict.
        let err = parse_lockfile_str(Path::new("mem"), &src);
        assert!(err.is_err(), "section header comment is not supported");
    }

    #[test]
    fn parse_lockfile_str_inline_comment_after_value() {
        let src = format!(
            "[targets]\n\
             \"x86_64-unknown-linux-gnu\" = \"sha256:{}\"  # from local publish\n",
            "d".repeat(64)
        );
        let lock = parse_lockfile_str(Path::new("mem"), &src).expect("parse");
        assert_eq!(lock.targets.len(), 1);
    }

    #[test]
    fn write_lockfile_append_only_merge_preserves_other_hosts() {
        let dir = tmp("merge");
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("addon.lock.toml");

        // Initial: linux-gnu only.
        let mut first = AddonLockfile::new();
        first.set_target(
            "x86_64-unknown-linux-gnu",
            format!("sha256:{}", "1".repeat(64)),
        );
        write_lockfile(&p, &first).expect("first write");

        // Second: add macOS; linux-gnu must survive.
        let mut second = AddonLockfile::new();
        second.set_target("aarch64-apple-darwin", format!("sha256:{}", "2".repeat(64)));
        write_lockfile(&p, &second).expect("second write");

        let merged = read_lockfile(&p).expect("read back");
        assert_eq!(merged.targets.len(), 2);
        assert_eq!(
            merged.get_target("x86_64-unknown-linux-gnu"),
            Some(&*format!("sha256:{}", "1".repeat(64)))
        );
        assert_eq!(
            merged.get_target("aarch64-apple-darwin"),
            Some(&*format!("sha256:{}", "2".repeat(64)))
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_lockfile_overwrites_same_host() {
        let dir = tmp("overwrite");
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("addon.lock.toml");

        // Original digest.
        let mut first = AddonLockfile::new();
        first.set_target(
            "x86_64-unknown-linux-gnu",
            format!("sha256:{}", "1".repeat(64)),
        );
        write_lockfile(&p, &first).expect("first write");

        // Rebuild on the same host, new digest.
        let mut second = AddonLockfile::new();
        second.set_target(
            "x86_64-unknown-linux-gnu",
            format!("sha256:{}", "9".repeat(64)),
        );
        write_lockfile(&p, &second).expect("second write");

        let merged = read_lockfile(&p).expect("read back");
        assert_eq!(merged.targets.len(), 1);
        assert_eq!(
            merged.get_target("x86_64-unknown-linux-gnu"),
            Some(&*format!("sha256:{}", "9".repeat(64)))
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_lockfile_rejects_invalid_sha_in_memory() {
        let dir = tmp("invalid");
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("addon.lock.toml");

        let mut lock = AddonLockfile::new();
        lock.targets.insert(
            "x86_64-unknown-linux-gnu".to_string(),
            "not-a-sha".to_string(),
        );
        let err = write_lockfile(&p, &lock).unwrap_err();
        matches!(err, LockfileError::InvalidSha256Format { .. });
        assert!(
            !p.exists(),
            "lockfile should not be written when validation fails"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn render_lockfile_is_lexicographic() {
        let mut lock = AddonLockfile::new();
        lock.set_target(
            "x86_64-unknown-linux-gnu",
            format!("sha256:{}", "1".repeat(64)),
        );
        lock.set_target("aarch64-apple-darwin", format!("sha256:{}", "2".repeat(64)));
        let out = render_lockfile(&lock);
        let linux_idx = out.find("x86_64-unknown-linux-gnu").expect("linux line");
        let darwin_idx = out.find("aarch64-apple-darwin").expect("darwin line");
        assert!(
            darwin_idx < linux_idx,
            "aarch64-apple-darwin should come before x86_64-unknown-linux-gnu lexicographically"
        );
    }

    #[test]
    fn render_lockfile_header_is_stable() {
        let lock = AddonLockfile::new();
        let out = render_lockfile(&lock);
        assert!(out.starts_with("# native/addon.lock.toml"));
        assert!(out.contains("[targets]"));
    }
}
