//! Cloudflare Workers JavaScript glue generation for the wasm-edge backend.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EdgeGlueMode {
    /// Execute `_start` and return stdout captured through the WASI fd bridge.
    Stdout,
    /// Dispatch Workers `fetch` requests through the explicit handler ABI.
    Handler,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EdgeGlueConfig<'a> {
    pub stem: &'a str,
    pub wasm_filename: &'a str,
    pub mode: EdgeGlueMode,
}

impl<'a> EdgeGlueConfig<'a> {
    pub fn stdout(stem: &'a str, wasm_filename: &'a str) -> Self {
        Self {
            stem,
            wasm_filename,
            mode: EdgeGlueMode::Stdout,
        }
    }

    pub fn handler(stem: &'a str, wasm_filename: &'a str) -> Self {
        Self {
            stem,
            wasm_filename,
            mode: EdgeGlueMode::Handler,
        }
    }
}

pub fn generate_edge_js_source(config: EdgeGlueConfig<'_>) -> String {
    match config.mode {
        EdgeGlueMode::Stdout => generate_stdout_edge_js_source(config.stem, config.wasm_filename),
        EdgeGlueMode::Handler => generate_handler_edge_js_source(config.stem, config.wasm_filename),
    }
}

pub fn generate_stdout_edge_js_source(stem: &str, wasm_filename: &str) -> String {
    format!(
        r#"// {stem}.edge.js -- Cloudflare Workers glue for Taida wasm-edge
// Generated by `taida build wasm-edge`
//
// Deploy: wrangler deploy --name {stem}
// wrangler.toml should set:
//   main = "{stem}.edge.js"
//   [wasm_modules]
//   WASM = "{wasm_filename}"

import WASM from "./{wasm_filename}";

export async function handleTaidaRequest(request, env, ctx) {{
    const stdoutChunks = [];
    const stderrChunks = [];

    let memory = new WebAssembly.Memory({{ initial: 2 }});
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();

    // -- helpers --

    function readStr(ptr, len) {{
      return decoder.decode(new Uint8Array(memory.buffer, ptr, len));
    }}

    function writeStr(ptr, str) {{
      const bytes = encoder.encode(str);
      new Uint8Array(memory.buffer, ptr, bytes.length).set(bytes);
      return bytes.length;
    }}

    // -- wasi_snapshot_preview1 --

    const wasi = {{
      fd_write(fd, iovs_ptr, iovs_len, nwritten_ptr) {{
        const view = new DataView(memory.buffer);
        let total = 0;
        for (let i = 0; i < iovs_len; i++) {{
          const base = iovs_ptr + i * 8;
          const ptr = view.getUint32(base, true);
          const len = view.getUint32(base + 4, true);
          const chunk = new Uint8Array(memory.buffer, ptr, len);
          if (fd === 1) {{
            stdoutChunks.push(new Uint8Array(chunk));
          }} else if (fd === 2) {{
            stderrChunks.push(new Uint8Array(chunk));
          }}
          total += len;
        }}
        view.setUint32(nwritten_ptr, total, true);
        return 0;
      }},
      // randomBytes entropy. crypto.getRandomValues is a CSPRNG; never
      // substitute Math.random here.
      random_get(buf_ptr, buf_len) {{
        const out = new Uint8Array(memory.buffer, buf_ptr, buf_len);
        for (let off = 0; off < buf_len; off += 65536) {{
          crypto.getRandomValues(out.subarray(off, Math.min(off + 65536, buf_len)));
        }}
        return 0;
      }},
      // nowMs wall clock (clock id is ignored; Date.now() is realtime).
      clock_time_get(_clock_id, _precision, out_ptr) {{
        new DataView(memory.buffer).setBigUint64(out_ptr, BigInt(Date.now()) * 1000000n, true);
        return 0;
      }},
    }};

    // -- taida_host --

    const taida_host = {{
      env_get(key_ptr, key_len, buf_ptr, buf_cap) {{
        const key = readStr(key_ptr, key_len);
        const val = env[key];
        if (val === undefined || val === null || typeof val !== "string") {{
          return 0;
        }}
        const bytes = encoder.encode(val);
        if (bytes.length > buf_cap) {{
          return bytes.length;
        }}
        new Uint8Array(memory.buffer, buf_ptr, bytes.length).set(bytes);
        return bytes.length;
      }},

      env_get_all(buf_ptr, buf_cap) {{
        const entries = [];
        for (const [k, v] of Object.entries(env)) {{
          if (typeof v === "string") {{
            entries.push(k + "=" + v);
          }}
        }}
        if (entries.length === 0) return 0;
        const payload = entries.join("\0") + "\0\0";
        const bytes = encoder.encode(payload);
        if (bytes.length > buf_cap) {{
          return bytes.length;
        }}
        new Uint8Array(memory.buffer, buf_ptr, bytes.length).set(bytes);
        return bytes.length;
      }},
    }};

    // -- instantiate and run --

    const importObject = {{
      env: {{ memory }},
      wasi_snapshot_preview1: wasi,
      taida_host,
    }};

    const instance = await WebAssembly.instantiate(WASM, importObject);

    // If the module exports its own memory, use that instead
    if (instance.exports.memory) {{
      memory = instance.exports.memory;
    }}

    if (instance.exports._start) {{
      instance.exports._start();
    }}

    // Log stderr to console
    if (stderrChunks.length > 0) {{
      const errBytes = concat(stderrChunks);
      console.error(decoder.decode(errBytes));
    }}

    // Return stdout as response
    const outBytes = concat(stdoutChunks);
    return new Response(decoder.decode(outBytes), {{
      headers: {{ "content-type": "text/plain; charset=utf-8" }},
    }});
}}

export default {{
  async fetch(request, env, ctx) {{
    return handleTaidaRequest(request, env, ctx);
  }},
}};

function concat(arrays) {{
  let total = 0;
  for (const a of arrays) total += a.length;
  const result = new Uint8Array(total);
  let offset = 0;
  for (const a of arrays) {{
    result.set(a, offset);
    offset += a.length;
  }}
  return result;
}}
"#,
        stem = stem,
        wasm_filename = wasm_filename,
    )
}

pub fn generate_handler_edge_js_source(stem: &str, wasm_filename: &str) -> String {
    format!(
        r#"// {stem}.edge.js -- Cloudflare Workers handler glue for Taida wasm-edge
// Generated by `taida build wasm-edge --handler <symbol>`
//
// Deploy: wrangler deploy --name {stem}
// wrangler.toml should set:
//   main = "{stem}.edge.js"
//   [wasm_modules]
//   WASM = "{wasm_filename}"

import WASM from "./{wasm_filename}";

export async function handleTaidaRequest(request, env, ctx) {{
    try {{
      const {{ instance, memory }} = await getInstance(env);
      const exports = instance.exports;
      const encoder = new TextEncoder();
      const decoder = new TextDecoder();

      const url = new URL(request.url);
      const headers = [];
      request.headers.forEach((value, key) => {{
        headers.push({{ name: key, value }});
      }});
      const query = [];
      url.searchParams.forEach((value, key) => {{
        query.push({{ name: key, value }});
      }});
      const bodyBase64 = arrayBufferToBase64(await request.arrayBuffer());
      const payload = JSON.stringify({{
        method: request.method,
        path: url.pathname,
        rawQuery: url.search.length > 0 ? url.search.slice(1) : "",
        query,
        headers,
        bodyBase64,
      }});

      const input = encoder.encode(payload);
      const inPtr = exports.taida_abi_web_alloc(input.length);
      if (!inPtr) {{
        return taidaErrorResponse(413, "request too large");
      }}
      new Uint8Array(memory.buffer, inPtr, input.length).set(input);

      const session = exports.taida_abi_web_start
        ? exports.taida_abi_web_start(inPtr, input.length)
        : exports.taida_abi_web_handle(inPtr, input.length);
      const raw = await readTaidaWebSession(exports, memory, decoder, encoder, session, env);

      const result = JSON.parse(raw);
      const responseHeaders = new Headers();
      for (const header of result.headers || []) {{
        if (header && typeof header.name === "string" && typeof header.value === "string") {{
          responseHeaders.append(header.name, header.value);
        }}
      }}
      const body = base64ToUint8Array(result.bodyBase64 || "");
      const status = clampStatus(result.status || 200);
      return new Response(body, {{
        status,
        headers: responseHeaders,
      }});
    }} catch (_err) {{
      return taidaErrorResponse(500, "handler failed");
    }}
}}

export default {{
  async fetch(request, env, ctx) {{
    return handleTaidaRequest(request, env, ctx);
  }},
}};

async function getInstance(env) {{
    let memory = new WebAssembly.Memory({{ initial: 2 }});
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();

    function readStr(ptr, len) {{
      return decoder.decode(new Uint8Array(memory.buffer, ptr, len));
    }}

    const wasi = {{
      fd_write(fd, iovs_ptr, iovs_len, nwritten_ptr) {{
        const view = new DataView(memory.buffer);
        let total = 0;
        for (let i = 0; i < iovs_len; i++) {{
          const base = iovs_ptr + i * 8;
          const len = view.getUint32(base + 4, true);
          total += len;
        }}
        view.setUint32(nwritten_ptr, total, true);
        return 0;
      }},
      // randomBytes entropy. crypto.getRandomValues is a CSPRNG; never
      // substitute Math.random here.
      random_get(buf_ptr, buf_len) {{
        const out = new Uint8Array(memory.buffer, buf_ptr, buf_len);
        for (let off = 0; off < buf_len; off += 65536) {{
          crypto.getRandomValues(out.subarray(off, Math.min(off + 65536, buf_len)));
        }}
        return 0;
      }},
      // nowMs wall clock (clock id is ignored; Date.now() is realtime).
      clock_time_get(_clock_id, _precision, out_ptr) {{
        new DataView(memory.buffer).setBigUint64(out_ptr, BigInt(Date.now()) * 1000000n, true);
        return 0;
      }},
    }};

    const taida_host = {{
      env_get(key_ptr, key_len, buf_ptr, buf_cap) {{
        const key = readStr(key_ptr, key_len);
        const val = env[key];
        if (val === undefined || val === null || typeof val !== "string") {{
          return 0;
        }}
        const bytes = encoder.encode(val);
        if (bytes.length > buf_cap) {{
          return bytes.length;
        }}
        new Uint8Array(memory.buffer, buf_ptr, bytes.length).set(bytes);
        return bytes.length;
      }},

      env_get_all(buf_ptr, buf_cap) {{
        const entries = [];
        for (const [k, v] of Object.entries(env)) {{
          if (typeof v === "string") {{
            entries.push(k + "=" + v);
          }}
        }}
        if (entries.length === 0) return 0;
        const payload = entries.join("\0") + "\0\0";
        const bytes = encoder.encode(payload);
        if (bytes.length > buf_cap) {{
          return bytes.length;
        }}
        new Uint8Array(memory.buffer, buf_ptr, bytes.length).set(bytes);
        return bytes.length;
      }},
    }};

    return WebAssembly.instantiate(WASM, {{
      env: {{ memory }},
      wasi_snapshot_preview1: wasi,
      taida_host,
    }}).then((instance) => {{
      if (instance.exports.memory) {{
        memory = instance.exports.memory;
      }}
      return {{ instance, memory }};
    }});
}}

async function readTaidaWebSession(exports, memory, decoder, encoder, session, env) {{
    for (let i = 0; i < 32; i++) {{
      const state = exports.taida_abi_web_poll ? exports.taida_abi_web_poll(session) : 0;
      if (state === 0) {{
        const outPtr = exports.taida_abi_web_out_ptr(session);
        const outLen = exports.taida_abi_web_out_len(session);
        if (!outPtr || outLen < 0) {{
          exports.taida_abi_web_free(session);
          throw new Error("invalid handler output");
        }}
        const raw = decoder.decode(new Uint8Array(memory.buffer, outPtr, outLen));
        exports.taida_abi_web_free(session);
        return raw;
      }}
      if (state === 1) {{
        if (!exports.taida_abi_web_resume) {{
          exports.taida_abi_web_free(session);
          throw new Error("host call resume unsupported");
        }}
        const outPtr = exports.taida_abi_web_out_ptr(session);
        const outLen = exports.taida_abi_web_out_len(session);
        if (!outPtr || outLen < 0) {{
          exports.taida_abi_web_free(session);
          throw new Error("invalid host call payload");
        }}
        const payload = JSON.parse(decoder.decode(new Uint8Array(memory.buffer, outPtr, outLen)));
        const resumePayload = await dispatchTaidaHostCall(payload, env);
        const resumeBytes = encoder.encode(JSON.stringify(resumePayload));
        const resumePtr = exports.taida_abi_web_alloc(resumeBytes.length);
        if (!resumePtr) {{
          exports.taida_abi_web_free(session);
          throw new Error("host call resume payload too large");
        }}
        new Uint8Array(memory.buffer, resumePtr, resumeBytes.length).set(resumeBytes);
        exports.taida_abi_web_resume(session, resumePtr, resumeBytes.length);
        continue;
      }}
      exports.taida_abi_web_free(session);
      throw new Error("handler ABI error");
    }}
    exports.taida_abi_web_free(session);
    throw new Error("handler ABI poll limit exceeded");
}}

async function dispatchTaidaHostCall(envelope, env) {{
    const id = envelope.id;
    try {{
      let target = env[envelope.capability];
      for (const step of envelope.steps) {{
        target = await target[step.method](...step.args);
      }}
      return {{ id, ok: true, value: target }};
    }} catch (err) {{
      return {{
        id,
        ok: false,
        error: err && err.message ? String(err.message) : String(err),
      }};
    }}
}}

function clampStatus(status) {{
  const n = Number.isFinite(status) ? Math.trunc(status) : 200;
  if (n < 100) return 100;
  if (n > 599) return 599;
  return n;
}}

function taidaErrorResponse(status, message) {{
  return new Response(message, {{
    status: clampStatus(status),
    headers: {{ "content-type": "text/plain; charset=utf-8", "x-taida-error": "abi" }},
  }});
}}

function arrayBufferToBase64(buffer) {{
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {{
    binary += String.fromCharCode(bytes[i]);
  }}
  return btoa(binary);
}}

function base64ToUint8Array(value) {{
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {{
    bytes[i] = binary.charCodeAt(i);
  }}
  return bytes;
}}
"#,
        stem = stem,
        wasm_filename = wasm_filename,
    )
}
