pub mod driver;
pub mod emit;
pub mod emit_wasm_c;
pub mod ir;
pub mod lower;
mod lower_json;
mod lower_methods;
mod lower_molds;
pub mod native_runtime;
pub mod rc_opt;
pub mod resolve;
pub mod runtime;
pub mod runtime_core_wasm;
pub(crate) mod tag_prop;
