/// Lockfile generation and parsing for Taida's package manager.
///
/// The lockfile (`taida.lock`) records the exact resolved state of all dependencies.
/// It is text-based, line-oriented, and designed for clean diffs in version control.
///
/// Format:
/// ```text
/// # taida.lock -- auto-generated by taida ingot install
/// # lockfile-version: 2
///
/// [[package]]
/// name = "taida-lang/os"
/// version = "1.0.0"
/// source = "bundled"
/// integrity = "sha256:abc123..."
///
/// [[package]]
/// name = "mylib"
/// version = "0.0.0-local"
/// source = "path:./libs/mylib"
/// integrity = "sha256:def456..."
///
/// [[package]]
/// name = "alice/webframework"
/// version = "b.12"
/// source = "github:alice/webframework"
/// integrity = "sha256:789abc..."
/// ```
use std::collections::HashMap;
use std::path::Path;

use super::provider::{PackageSource, ResolvedPackage, compute_dir_hash};

/// The current lockfile format version.
pub const LOCKFILE_VERSION: u32 = 2;
const LEGACY_LOCKFILE_VERSION: u32 = 1;

/// A parsed lockfile.
#[derive(Debug, Clone)]
pub struct Lockfile {
    /// Format version.
    pub version: u32,
    /// Locked packages, sorted by name.
    pub packages: Vec<LockedPackage>,
}

/// A single locked package entry.
#[derive(Debug, Clone, PartialEq)]
pub struct LockedPackage {
    /// Package name.
    pub name: String,
    /// Resolved version.
    pub version: String,
    /// Source descriptor (e.g. "bundled:taida-lang/os", "path:./libs/mylib").
    pub source: String,
    /// Integrity hash.
    pub integrity: String,
    /// RC1.5: Optional addon binary info.
    pub addon: Option<LockedAddon>,
}

/// RC1.5: Locked addon binary metadata.
#[derive(Debug, Clone, PartialEq)]
pub struct LockedAddon {
    /// Target triple (e.g. "x86_64-unknown-linux-gnu").
    pub target: String,
    /// SHA-256 hex digest of the prebuild binary.
    pub sha256: String,
}

impl Lockfile {
    /// Generate a lockfile from resolved packages.
    pub fn from_resolved(packages: &[ResolvedPackage]) -> Self {
        let mut locked: Vec<LockedPackage> = packages
            .iter()
            .map(|pkg| LockedPackage {
                name: pkg.name.clone(),
                version: pkg.version.clone(),
                source: source_to_string(&pkg.source),
                integrity: pkg.integrity.clone(),
                addon: None, // caller should extend via with_addon if needed
            })
            .collect();

        // Sort by name for deterministic output
        locked.sort_by(|a, b| a.name.cmp(&b.name));

        Lockfile {
            version: LOCKFILE_VERSION,
            packages: locked,
        }
    }

    /// RC1.5: Attach addon info to a package entry.
    /// Returns Err if the package is not in the lockfile.
    pub fn with_addon(
        &mut self,
        package_name: &str,
        target: String,
        sha256: String,
    ) -> Result<(), String> {
        let pkg = self
            .packages
            .iter_mut()
            .find(|p| p.name == package_name)
            .ok_or_else(|| format!("package '{package_name}' not found in lockfile"))?;
        pkg.addon = Some(LockedAddon { target, sha256 });
        Ok(())
    }

    /// Write the lockfile to disk.
    pub fn write(&self, path: &Path) -> Result<(), String> {
        let content = self.to_string();
        std::fs::write(path, content)
            .map_err(|e| format!("Cannot write lockfile '{}': {}", path.display(), e))
    }

    /// Read and parse a lockfile from disk.
    /// Returns None if the file does not exist.
    pub fn read(path: &Path) -> Result<Option<Self>, String> {
        if !path.exists() {
            return Ok(None);
        }

        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("Cannot read lockfile '{}': {}", path.display(), e))?;

        Self::parse(&content).map(Some)
    }

    /// Read and parse a legacy lockfile for explicit migration only.
    pub fn read_for_migration(path: &Path) -> Result<Option<Self>, String> {
        if !path.exists() {
            return Ok(None);
        }

        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("Cannot read lockfile '{}': {}", path.display(), e))?;

        Self::parse_inner(&content, true).map(Some)
    }

    /// Parse lockfile content from a string.
    pub fn parse(content: &str) -> Result<Self, String> {
        Self::parse_inner(content, false)
    }

    fn parse_inner(content: &str, allow_legacy: bool) -> Result<Self, String> {
        let mut version = LEGACY_LOCKFILE_VERSION;
        let mut packages = Vec::new();
        let mut current_pkg: Option<LockedPackageBuilder> = None;
        // RC1.5: track whether we're inside [[package.addon]]
        let mut in_addon = false;

        for line in content.lines() {
            let line = line.trim();

            // Skip empty lines and comments
            if line.is_empty() {
                continue;
            }

            if line.starts_with('#') {
                // Check for version comment
                if let Some(rest) = line.strip_prefix("# lockfile-version: ") {
                    version = rest.trim().parse().unwrap_or(LOCKFILE_VERSION);
                }
                continue;
            }

            if line == "[[package]]" {
                // Flush previous package
                if let Some(builder) = current_pkg.take() {
                    packages.push(builder.build()?);
                }
                current_pkg = Some(LockedPackageBuilder::new());
                in_addon = false;
                continue;
            }

            // RC1.5: [[package.addon]] subtable
            if line.starts_with("[[package.addon]]") {
                in_addon = true;
                continue;
            }

            // Parse key = "value" lines
            if let Some(kv) = parse_kv_line(line) {
                let (key, value) = kv;
                if let Some(builder) = &mut current_pkg {
                    if in_addon {
                        // RC1.5: parse addon fields
                        match key {
                            "target" => builder.addon_target = Some(value.to_string()),
                            "sha256" => builder.addon_sha256 = Some(value.to_string()),
                            _ => {}
                        }
                    } else {
                        match key {
                            "name" => builder.name = Some(value.to_string()),
                            "version" => builder.version = Some(value.to_string()),
                            "source" => builder.source = Some(value.to_string()),
                            "integrity" => builder.integrity = Some(value.to_string()),
                            _ => {} // Ignore unknown keys for forward compatibility
                        }
                    }
                }
            }
        }

        // Flush last package
        if let Some(builder) = current_pkg {
            packages.push(builder.build()?);
        }

        let lockfile = Lockfile { version, packages };
        lockfile.validate_schema(allow_legacy)?;
        Ok(lockfile)
    }

    fn validate_schema(&self, allow_legacy: bool) -> Result<(), String> {
        if self.version < LOCKFILE_VERSION && !allow_legacy {
            return Err(format!(
                "[E32K2_LOCKFILE_V1_REJECTED] taida.lock schema v{} is no longer accepted; run `taida ingot migrate-lockfile`",
                self.version
            ));
        }
        if self.version > LOCKFILE_VERSION {
            return Err(format!(
                "[E32K2_LOCKFILE_UNSUPPORTED_VERSION] taida.lock schema v{} is newer than this taida binary supports (current v{})",
                self.version, LOCKFILE_VERSION
            ));
        }

        for pkg in &self.packages {
            if pkg.integrity.starts_with("fnv1a:") {
                if !allow_legacy {
                    return Err(format!(
                        "[E32K2_LOCKFILE_V1_REJECTED] package '{}' uses legacy fnv1a integrity; run `taida ingot migrate-lockfile`",
                        pkg.name
                    ));
                }
                // Legacy fnv1a: opaque payload is left to the migration path.
                continue;
            }
            // Any value claiming to be sha256 must match the canonical
            // `sha256:` + 64 lowercase hex shape. The check runs in both
            // `read` (allow_legacy=true) and `parse` (allow_legacy=false) so
            // that a malformed sha256 lockfile cannot silently slip through
            // `is_up_to_date` and be rewritten by the resolver — migration
            // must go through `taida ingot migrate-lockfile` instead.
            if pkg.integrity.starts_with("sha256:") {
                if !is_valid_lockfile_integrity(&pkg.integrity) {
                    return Err(format!(
                        "[E32K2_LOCKFILE_INTEGRITY_MISMATCH] package '{}' has malformed integrity '{}'; expected sha256: + 64 lowercase hex characters. To recover, run `taida ingot migrate-lockfile`, or delete `.taida/taida.lock` and rerun `taida ingot install` to regenerate it.",
                        pkg.name, pkg.integrity
                    ));
                }
                continue;
            }
            if !allow_legacy {
                return Err(format!(
                    "[E32K2_LOCKFILE_INTEGRITY_MISMATCH] package '{}' has unsupported integrity '{}'. To recover, run `taida ingot migrate-lockfile`, or delete `.taida/taida.lock` and rerun `taida ingot install` to regenerate it.",
                    pkg.name, pkg.integrity
                ));
            }
        }

        Ok(())
    }

    /// Check if the lockfile is up to date with the given resolved packages.
    /// Returns true if all resolved packages match the locked entries.
    pub fn is_up_to_date(&self, resolved: &[ResolvedPackage]) -> bool {
        // A malformed integrity value must never be treated as "still
        // valid" because that lets `taida ingot install` rewrite the
        // lockfile from a tampered draft instead of forcing the user
        // through `taida ingot migrate-lockfile`.
        if self.version != LOCKFILE_VERSION
            || self
                .packages
                .iter()
                .any(|pkg| !is_valid_lockfile_integrity(&pkg.integrity))
        {
            return false;
        }
        if self.packages.len() != resolved.len() {
            return false;
        }

        let locked_by_name: std::collections::HashMap<&str, &LockedPackage> =
            self.packages.iter().map(|p| (p.name.as_str(), p)).collect();

        for pkg in resolved {
            match locked_by_name.get(pkg.name.as_str()) {
                Some(locked) => {
                    if locked.version != pkg.version
                        || locked.integrity != pkg.integrity
                        || locked.source != source_to_string(&pkg.source)
                    {
                        return false;
                    }
                }
                None => return false,
            }
        }

        true
    }

    /// Validate the lockfile as the binding source of truth for install.
    pub fn validate_resolved_bindings(&self, resolved: &[ResolvedPackage]) -> Result<(), String> {
        self.validate_schema(false)?;

        let locked_by_name: HashMap<&str, &LockedPackage> =
            self.packages.iter().map(|p| (p.name.as_str(), p)).collect();

        for pkg in resolved {
            let locked = locked_by_name.get(pkg.name.as_str()).ok_or_else(|| {
                format!(
                    "[E32K2_LOCKFILE_INTEGRITY_MISMATCH] package '{}' is resolved but missing from taida.lock; run `taida ingot update` or remove --frozen",
                    pkg.name
                )
            })?;
            let expected_source = source_to_string(&pkg.source);
            if locked.version != pkg.version
                || locked.integrity != pkg.integrity
                || locked.source != expected_source
            {
                return Err(format!(
                    "[E32K2_LOCKFILE_INTEGRITY_MISMATCH] package '{}' lockfile triple mismatch (lock version={}, source={}, integrity={}; resolved version={}, source={}, integrity={})",
                    pkg.name,
                    locked.version,
                    locked.source,
                    locked.integrity,
                    pkg.version,
                    expected_source,
                    pkg.integrity
                ));
            }
        }

        if self.packages.len() != resolved.len() {
            return Err(format!(
                "[E32K2_LOCKFILE_INTEGRITY_MISMATCH] taida.lock has {} package(s) but resolver produced {}",
                self.packages.len(),
                resolved.len()
            ));
        }

        Ok(())
    }

    /// Explicit v1/fnv1a -> v2/sha256 migration using installed dependency dirs.
    pub fn migrate_v2_from_installed(lock_path: &Path, deps_dir: &Path) -> Result<Self, String> {
        let mut lockfile = Self::read_for_migration(lock_path)?
            .ok_or_else(|| "[E32K2_LOCKFILE_MIGRATE_FAIL] taida.lock not found".to_string())?;

        if lockfile.version >= LOCKFILE_VERSION
            && lockfile
                .packages
                .iter()
                .all(|pkg| pkg.integrity.starts_with("sha256:"))
        {
            return Ok(lockfile);
        }

        for pkg in &mut lockfile.packages {
            let dep_path = deps_dir.join(&pkg.name);
            if !dep_path.exists() {
                return Err(format!(
                    "[E32K2_LOCKFILE_MIGRATE_FAIL] installed dependency '{}' not found at '{}'",
                    pkg.name,
                    dep_path.display()
                ));
            }
            pkg.integrity = compute_dir_hash(&dep_path).map_err(|e| {
                format!(
                    "[E32K2_LOCKFILE_MIGRATE_FAIL] cannot compute SHA-256 for '{}': {}",
                    pkg.name, e
                )
            })?;
        }

        lockfile.version = LOCKFILE_VERSION;
        lockfile.write(lock_path)?;
        Ok(lockfile)
    }
}

impl std::fmt::Display for Lockfile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut out = String::new();
        out.push_str("# taida.lock -- auto-generated by taida ingot install\n");
        out.push_str(&format!("# lockfile-version: {}\n", self.version));

        for pkg in &self.packages {
            out.push('\n');
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", pkg.name));
            out.push_str(&format!("version = \"{}\"\n", pkg.version));
            out.push_str(&format!("source = \"{}\"\n", pkg.source));
            out.push_str(&format!("integrity = \"{}\"\n", pkg.integrity));

            // RC1.5: optional [[package.addon]] subtable
            if let Some(ref addon) = pkg.addon {
                out.push('\n');
                out.push_str("  [[package.addon]]\n");
                out.push_str(&format!("  target = \"{}\"\n", addon.target));
                out.push_str(&format!("  sha256 = \"{}\"\n", addon.sha256));
            }
        }

        write!(f, "{}", out)
    }
}

/// Builder for parsing lockfile package entries.
#[derive(Default)]
struct LockedPackageBuilder {
    name: Option<String>,
    version: Option<String>,
    source: Option<String>,
    integrity: Option<String>,
    // RC1.5: optional addon fields
    addon_target: Option<String>,
    addon_sha256: Option<String>,
}

impl LockedPackageBuilder {
    fn new() -> Self {
        Self::default()
    }

    fn build(self) -> Result<LockedPackage, String> {
        let addon = match (self.addon_target, self.addon_sha256) {
            (Some(target), Some(sha256)) => Some(LockedAddon { target, sha256 }),
            _ => None, // both absent -> None (backward compat)
        };
        Ok(LockedPackage {
            name: self.name.ok_or("lockfile: package missing 'name' field")?,
            version: self
                .version
                .ok_or("lockfile: package missing 'version' field")?,
            source: self
                .source
                .ok_or("lockfile: package missing 'source' field")?,
            integrity: self
                .integrity
                .ok_or("lockfile: package missing 'integrity' field")?,
            addon,
        })
    }
}

/// Parse a `key = "value"` line. Returns (key, value) with quotes stripped.
fn parse_kv_line(line: &str) -> Option<(&str, &str)> {
    let eq_pos = line.find('=')?;
    let key = line[..eq_pos].trim();
    let value = line[eq_pos + 1..].trim();

    // Strip surrounding quotes
    let value = if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
        &value[1..value.len() - 1]
    } else {
        value
    };

    Some((key, value))
}

/// A lockfile `integrity` value is only canonical when it is exactly
/// `sha256:` followed by 64 lowercase hex characters. A bare prefix check
/// such as `starts_with("sha256:")` would let `sha256:`, `sha256:0`, and
/// non-hex payloads slip through schema validation and `is_up_to_date`,
/// leaving the resolver free to silently rewrite a tampered draft.
fn is_valid_lockfile_integrity(value: &str) -> bool {
    let Some(hex) = value.strip_prefix("sha256:") else {
        return false;
    };
    hex.len() == 64
        && hex
            .chars()
            .all(|c| c.is_ascii_digit() || matches!(c, 'a'..='f'))
}

/// Convert a PackageSource to a lockfile source string.
fn source_to_string(source: &PackageSource) -> String {
    match source {
        PackageSource::Path(p) => format!("path:{}", p),
        PackageSource::CoreBundled => "bundled".to_string(),
        PackageSource::Store { org, name } => format!("github:{}/{}", org, name),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn make_resolved(name: &str, version: &str, source: PackageSource) -> ResolvedPackage {
        ResolvedPackage {
            name: name.to_string(),
            version: version.to_string(),
            source,
            path: PathBuf::from("/tmp/test"),
            integrity: format!("sha256:{:064x}", name.len()),
        }
    }

    #[test]
    fn test_lockfile_roundtrip() {
        let packages = vec![
            make_resolved("os", "1.0.0", PackageSource::CoreBundled),
            make_resolved(
                "mylib",
                "0.0.0-local",
                PackageSource::Path("./libs/mylib".to_string()),
            ),
        ];

        let lockfile = Lockfile::from_resolved(&packages);
        let serialized = lockfile.to_string();

        // Parse back
        let parsed = Lockfile::parse(&serialized).unwrap();
        assert_eq!(parsed.version, 2);
        assert_eq!(parsed.packages.len(), 2);

        // Should be sorted by name: mylib, os
        assert_eq!(parsed.packages[0].name, "mylib");
        assert_eq!(parsed.packages[0].version, "0.0.0-local");
        assert_eq!(parsed.packages[0].source, "path:./libs/mylib");

        assert_eq!(parsed.packages[1].name, "os");
        assert_eq!(parsed.packages[1].version, "1.0.0");
        assert_eq!(parsed.packages[1].source, "bundled");
    }

    #[test]
    fn test_lockfile_write_and_read() {
        let dir = PathBuf::from("/tmp/taida_test_lockfile");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let packages = vec![make_resolved("os", "1.0.0", PackageSource::CoreBundled)];

        let lockfile = Lockfile::from_resolved(&packages);
        let lock_path = dir.join("taida.lock");

        lockfile.write(&lock_path).unwrap();
        assert!(lock_path.exists());

        let read_back = Lockfile::read(&lock_path).unwrap().unwrap();
        assert_eq!(read_back.packages.len(), 1);
        assert_eq!(read_back.packages[0].name, "os");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_lockfile_read_nonexistent() {
        let result = Lockfile::read(Path::new("/tmp/nonexistent_taida_lock")).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn test_lockfile_is_up_to_date() {
        let packages = vec![make_resolved("os", "1.0.0", PackageSource::CoreBundled)];

        let lockfile = Lockfile::from_resolved(&packages);
        assert!(lockfile.is_up_to_date(&packages));

        // Different version -> not up to date
        let changed = vec![make_resolved("os", "2.0.0", PackageSource::CoreBundled)];
        assert!(!lockfile.is_up_to_date(&changed));

        // Additional package -> not up to date
        let extra = vec![
            make_resolved("os", "1.0.0", PackageSource::CoreBundled),
            make_resolved("extra", "0.1.0", PackageSource::Path("./extra".to_string())),
        ];
        assert!(!lockfile.is_up_to_date(&extra));
    }

    #[test]
    fn test_lockfile_empty() {
        let lockfile = Lockfile::from_resolved(&[]);
        let serialized = lockfile.to_string();
        let parsed = Lockfile::parse(&serialized).unwrap();
        assert!(parsed.packages.is_empty());
    }

    #[test]
    fn test_lockfile_format_is_diffable() {
        let packages = vec![
            make_resolved("alpha", "1.0.0", PackageSource::CoreBundled),
            make_resolved("beta", "2.0.0", PackageSource::Path("./beta".to_string())),
        ];

        let lockfile = Lockfile::from_resolved(&packages);
        let text = lockfile.to_string();

        // Each package should start on its own line with [[package]]
        assert!(text.contains("[[package]]"));
        // Values should be on separate lines (diffable)
        assert!(text.contains("name = \"alpha\""));
        assert!(text.contains("name = \"beta\""));
        // Should have the header comment
        assert!(text.contains("# taida.lock"));
        assert!(text.contains("# lockfile-version: 2"));
    }

    #[test]
    fn test_lockfile_roundtrip_with_store_source() {
        let packages = vec![
            make_resolved("taida-lang/os", "1.0.0", PackageSource::CoreBundled),
            make_resolved(
                "alice/webframework",
                "b.12",
                PackageSource::Store {
                    org: "alice".to_string(),
                    name: "webframework".to_string(),
                },
            ),
        ];

        let lockfile = Lockfile::from_resolved(&packages);
        let serialized = lockfile.to_string();

        // Verify github: source format in output
        assert!(serialized.contains("source = \"github:alice/webframework\""));

        // Parse back
        let parsed = Lockfile::parse(&serialized).unwrap();
        assert_eq!(parsed.packages.len(), 2);

        // Sorted by name: alice/webframework, taida-lang/os
        assert_eq!(parsed.packages[0].name, "alice/webframework");
        assert_eq!(parsed.packages[0].version, "b.12");
        assert_eq!(parsed.packages[0].source, "github:alice/webframework");

        assert_eq!(parsed.packages[1].name, "taida-lang/os");
        assert_eq!(parsed.packages[1].source, "bundled");
    }

    #[test]
    fn test_parse_kv_line() {
        assert_eq!(parse_kv_line("name = \"hello\""), Some(("name", "hello")));
        assert_eq!(
            parse_kv_line("version = \"1.0.0\""),
            Some(("version", "1.0.0"))
        );
        assert_eq!(parse_kv_line("key=value"), Some(("key", "value")));
        assert_eq!(parse_kv_line("no equals sign"), None);
    }

    // ── RC1.5: Lockfile addon subtable tests ─────────────────────

    #[test]
    fn test_lockfile_with_addon_roundtrip() {
        let packages = vec![make_resolved(
            "taida-lang/terminal",
            "a.1",
            PackageSource::CoreBundled,
        )];
        let mut lockfile = Lockfile::from_resolved(&packages);
        lockfile
            .with_addon(
                "taida-lang/terminal",
                "x86_64-unknown-linux-gnu".to_string(),
                "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                    .to_string(),
            )
            .unwrap();

        let serialized = lockfile.to_string();
        assert!(serialized.contains("[[package.addon]]"));
        assert!(serialized.contains("target = \"x86_64-unknown-linux-gnu\""));
        assert!(serialized.contains("sha256 = \"sha256:aaa"));

        let parsed = Lockfile::parse(&serialized).unwrap();
        assert_eq!(parsed.packages.len(), 1);
        let addon = parsed.packages[0].addon.as_ref().unwrap();
        assert_eq!(addon.target, "x86_64-unknown-linux-gnu");
        assert!(addon.sha256.starts_with("sha256:aa"));
    }

    #[test]
    fn test_lockfile_v1_fnv1a_rejected() {
        let content = r#"# taida.lock -- auto-generated by taida ingot install
# lockfile-version: 1

[[package]]
name = "os"
version = "1.0.0"
source = "bundled"
integrity = "fnv1a:0000000000000002"
"#;
        let err = Lockfile::parse(content).unwrap_err();
        assert!(err.contains("[E32K2_LOCKFILE_V1_REJECTED]"));

        let parsed = Lockfile::parse_inner(content, true).unwrap();
        assert_eq!(parsed.version, 1);
        assert_eq!(parsed.packages[0].integrity, "fnv1a:0000000000000002");
    }

    /// Schema validation must reject lockfiles whose `integrity` values
    /// look like `sha256:...` but are not exactly 64 lowercase hex
    /// characters. A bare `starts_with("sha256:")` check would accept
    /// `sha256:` (empty), `sha256:0` (too short), and non-hex tails.
    #[test]
    fn test_lockfile_malformed_sha256_integrity_rejected() {
        for malformed in [
            "sha256:",
            "sha256:0",
            "sha256:0123456789abcdef", // 16 hex
            "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", // 63 hex
            "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdefa", // 65 hex
            "sha256:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", // non-hex
            "sha256:0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF", // upper-case
        ] {
            let content = format!(
                r#"# taida.lock -- auto-generated by taida ingot install
# lockfile-version: 2

[[package]]
name = "os"
version = "1.0.0"
source = "bundled"
integrity = "{malformed}"
"#
            );
            let err = Lockfile::parse(&content).expect_err("malformed integrity must reject");
            assert!(
                err.contains("[E32K2_LOCKFILE_INTEGRITY_MISMATCH]") && err.contains("malformed"),
                "malformed integrity '{malformed}' was not rejected; got: {err}"
            );
        }
    }

    /// A malformed integrity must also force `is_up_to_date` to return
    /// false so the resolver cannot silently rewrite the lockfile.
    #[test]
    fn test_is_up_to_date_rejects_malformed_integrity() {
        let lockfile = Lockfile {
            version: LOCKFILE_VERSION,
            packages: vec![LockedPackage {
                name: "os".to_string(),
                version: "1.0.0".to_string(),
                source: "bundled".to_string(),
                integrity: "sha256:0".to_string(),
                addon: None,
            }],
        };
        let resolved = vec![make_resolved("os", "1.0.0", PackageSource::CoreBundled)];
        assert!(
            !lockfile.is_up_to_date(&resolved),
            "malformed integrity must invalidate is_up_to_date so the resolver \
             does not silently overwrite a tampered lockfile"
        );
    }

    /// The canonical shape (sha256: + 64 lowercase hex) must keep passing
    /// both `validate_schema` and `is_up_to_date`.
    #[test]
    fn test_canonical_sha256_integrity_accepted() {
        let valid = "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
        let content = format!(
            r#"# taida.lock -- auto-generated by taida ingot install
# lockfile-version: 2

[[package]]
name = "os"
version = "1.0.0"
source = "bundled"
integrity = "{valid}"
"#
        );
        let lockfile = Lockfile::parse(&content).expect("canonical integrity must parse");
        assert_eq!(lockfile.packages[0].integrity, valid);
        let resolved = vec![ResolvedPackage {
            name: "os".to_string(),
            version: "1.0.0".to_string(),
            source: PackageSource::CoreBundled,
            path: PathBuf::from("/tmp/test"),
            integrity: valid.to_string(),
        }];
        assert!(lockfile.is_up_to_date(&resolved));
    }

    #[test]
    fn test_is_valid_lockfile_integrity_helper() {
        assert!(is_valid_lockfile_integrity(
            "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
        ));
        assert!(!is_valid_lockfile_integrity("sha256:"));
        assert!(!is_valid_lockfile_integrity("sha256:0"));
        assert!(!is_valid_lockfile_integrity(
            "sha256:0123456789ABCDEF0123456789abcdef0123456789abcdef0123456789abcdef"
        ));
        assert!(!is_valid_lockfile_integrity(
            "sha256:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
        ));
        assert!(!is_valid_lockfile_integrity(
            "fnv1a:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
        ));
    }

    #[test]
    fn test_lockfile_with_addon_display_indent() {
        let packages = vec![make_resolved("org/pkg", "a.1", PackageSource::CoreBundled)];
        let mut lockfile = Lockfile::from_resolved(&packages);
        lockfile
            .with_addon(
                "org/pkg",
                "x86_64-unknown-linux-gnu".to_string(),
                "sha256:bbb".to_string(),
            )
            .unwrap();
        let serialized = lockfile.to_string();
        // Subtable should be indented with 2 spaces
        assert!(serialized.contains("  [[package.addon]]"));
        assert!(serialized.contains("  target = "));
    }
}
